# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: wilhelmfermey <marvin@42.fr>               +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/07/14 11:04:32 by wilhelmfermey     #+#    #+#              #
#    Updated: 2022/07/14 11:15:58 by wilhelmfermey    ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME:	megaphone

FLAGS:	-Wall -Wextra -Werror

FILES:	megaphone.cpp

${NAME}:
			g++ ${FLAGS} ${FILES} -o ${NAME}

all:	${NAME}

clean:
			rm megaphone

fclean:	
			rm megaphone

re:			fclean all
