NAME=	Zombie	

FLAGS=	-Wall -Wextra -Werror

FILES=	main.cpp Zombie.cpp zombieHorde.cpp

${NAME}:	
		g++ ${FLAGS} ${FILES} -o ${NAME}

all:	${NAME}

clean:
		rm ${NAME}

fclean:
		rm ${NAME}

re:		fclean all
