# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: wilhelmfermey <marvin@42.fr>               +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/07/14 11:24:35 by wilhelmfermey     #+#    #+#              #
#    Updated: 2022/07/15 15:01:09 by wilhelmfermey    ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME=	Phonebook

FLAGS=	-Wall -Wextra -Werror

FILES=	main.cpp Phonebook.class.cpp Contact.class.cpp

${NAME}:
			g++ ${FLAGS} ${FILES} -o ${NAME}

all:	${NAME}

clean:		
		rm ${NAME}

fclean:		
		rm ${NAME}

re:		fclean all		
